car2_inventory/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email

class UserLoginForm(FlaskForm):
    # email, password, submit_button
    email = StringField('Email', validators = [DataRequired(), Email()])
    password = PasswordField('Password', validators = [DataRequired()])
    submit_button = SubmitField()

car2_inventory/api/routes.py
from flask import Blueprint

api = Blueprint('api', __name__, url_prefix = '/api')

@api.route('/getdata')
def getdata():
    return { 'some': 'value'}

car2_inventory/authentication/routes.py
from flask import Blueprint, render_template, request, redirect,url_for,flash
# from drone_inventory.models import User,db
# from drone_inventory.forms import UserLoginForm


auth = Blueprint('auth', __name__, template_folder = 'auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserLoginForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email,password)

            user = User(email, password = password)

            db.session.add(user)
            db.session.commit()

            flash(f'You have successfully created a user account {email}', 'user-created')

            return redirect(url_for('site.home'))

    except:
        raise Exception('Invalid Form Data: Please Check your form')
    return render_template('signup.html', form=form)

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    return render_template('signin.html')

car2_inventory/site/routes.py
from flask import Blueprint, render_template

"""
Note that in the above code, 
some arguments are specified when creating the Blueprint object. 
The first argument, "site", is the Blueprint’s name, 
which is used by Flask’s routing mechanism. 
The second argument, __name__, is the Blueprint’s import name, 
which Flask uses to locate the Blueprint’s resources.
"""

site = Blueprint('site',__name__,template_foldder='site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('profile')
def profile():
    return render_template('profile.html')

car2_inventory/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../../static/css/main.css">
<title>Cars Inventory API</title>
</head>
<body>

    <!--NavBar 4ever-->
    <nav class="ct-nav">
        <div>
            <img src="../../static/images/Coding Drones Logo.png" alt="Coding drones logo">
        </div>

         <!--Nav Items-->
         <div>
            <ul id="horizontal-list">
                <a href="{{ url_for('site.home') }}">
                    <li>The Coding Cars Project</li>
                </a>
                <a href="">
                    <li>Donate</li>
                </a>
                <a href="{{ url_for('site.profile') }}">
                    <li>Profile</li>
                </a>
                <!--User Auth Check for SignIn/SignUp Nav Buttons-->
                {% if current_user.is_authenticated %}
                <a href="{{ url_for('auth.logout') }}">
                    <li>Log Out</li>
                </a>
                {% else %}
                <a href="{{ url_for('auth.signin') }}">
                    <li>Sign In</li>
                </a>
                <a href="{{ url_for('auth.signup') }}">
                    <li>Sign Up Free</li>
                </a>
                {% endif %}
            </ul>
        </div>
      </nav>
      <!--End of Nav-->

    {% block content %}
    {% endblock content %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>